# filepath: netlify.toml
[functions]
directory = "../netlify/functions/proxy-server"

[build]
base = "Assignment-Salesforce/salesforce-validation-application"
publish = "dist"
command = "npm run build"