# filepath: netlify.toml
[functions]
directory = "../netlify/functions"

[build]
base = "Assignment Salesforce (2nd Round)/salesforce-validation-application"
publish = "dist"
command = "npm run build"